**ONE HOT ENCODING**

In [ ]:
import pandas as pd

In [ ]:
dataset = pd.read_csv("loan.csv")

In [1]:
dataset.head(100)

NameError: name 'dataset' is not defined

In [ ]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
dataset['Gender'].fillna(dataset["Gender"].mode()[0] , inplace = True)

/tmp/ipykernel_5888/4121655321.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Gender'].fillna(dataset["Gender"].mode()[0] , inplace = True)

In [ ]:
dataset['Married'].fillna(dataset["Married"].mode()[0] , inplace = True)

/tmp/ipykernel_5888/3200640796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married'].fillna(dataset["Married"].mode()[0] , inplace = True)

In [ ]:
en_data = dataset[["Gender" , "Married"]]

In [ ]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop="first")
ar = ohe.fit_transform(en_data).toarray()
ar

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [ ]:
pd.DataFrame(ar , columns = ["Gender_Male" ,  "Married_Yes "])

     Gender_Male  Married_Yes
0            1.0           0.0
1            1.0           1.0
2            1.0           1.0
3            1.0           1.0
4            1.0           0.0
..           ...           ...
609          0.0           0.0
610          1.0           1.0
611          1.0           1.0
612          1.0           1.0
613          0.0           0.0

[614 rows x 2 columns]

**LABEL ENCODING**

In [ ]:
#Custom Dataset
df = pd.DataFrame( { "name" : ["Bhavya" , "Lion" , "Cat" , "Youtube" , "Instagram"] })
df

        name
0     Bhavya
1       Lion
2        Cat
3    Youtube
4  Instagram

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
df ["en_name"] = le.fit_transform(df [["name"]])
df

        name  en_name
0     Bhavya        0
1       Lion        3
2        Cat        1
3    Youtube        4
4  Instagram        2

In [ ]:
dataset = pd.read_csv("loan.csv")
dataset.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [ ]:
dataset["Property_Area"].unique()

array([2, 0, 1])

In [ ]:
la = LabelEncoder()
la.fit(dataset["Property_Area"])

LabelEncoder()

In [ ]:
dataset["Property_Area"] = la.fit_transform(dataset["Property_Area"])

**ODINAL ENCODING**

In [ ]:
#New Dataset
new_df = pd.DataFrame({"Size": ["s", "m", "l","xl", "s" , "m", "l","s", "s", "l", "xl", "m"]})
new_df.head(3)

In [ ]:
ord_data = [["s" , "m" , "l" , "xl"]]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(new_df[["Size"]] )

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [ ]:
new_df["Size_en"] = oe.transform(new_df[["Size"]] )
new_df

   Size  Size_en
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

**ORDINAL ENCODING USING MAP FUN**

In [ ]:
ord_data1 = { "s":5 , "m":6 , "l":7 , "xl":10 }

In [ ]:
new_df["Size_en.map"] = new_df["Size"].map(ord_data1)
new_df

   Size  Size_en  Size_en.map
0     s      0.0            5
1     m      1.0            6
2     l      2.0            7
3    xl      3.0           10
4     s      0.0            5
5     m      1.0            6
6     l      2.0            7
7     s      0.0            5
8     s      0.0            5
9     l      2.0            7
10   xl      3.0           10
11    m      1.0            6

**ORDINAL ENCODING ON LOAN.CSV DATASET**

In [ ]:
loan_df = pd.read_csv("loan.csv")
loan_df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [ ]:
loan_df["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [ ]:
loan_ord =  [["Rural" , "Semiurban" , "Urban"]]

In [ ]:
loan_oe = OrdinalEncoder(categories=loan_ord)
loan_df["Property_Area"] = loan_oe.fit_transform(loan_df[["Property_Area"]])

In [ ]:
loan_df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0.0,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0.0,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2.0,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2.0,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1.0,N