In [39]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.model_selection import cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

In [2]:
dataset = pd.read_csv("/Users/bhavyakansal/Downloads/train.csv")
dataset.head(10)

                                        message_text          class_label
0  New water meter installation scheduled at your...               benign
1  Your water account 5774836158 has no pending d...               benign
2  BOI Security: Transaction of Rs.2135 from acco...        impersonation
3  BWSSB Notice: Pending water bill Rs.20462 for ...             kyc_scam
4  KYC expired. Update within 2 hours to avoid ac...        phishing_link
5  Bank notice: Please ignore suspicious calls/SM...               benign
6  LPG connection blocked. Reactivate by paying R...  fake_payment_portal
7  EMI of Rs.6941 auto-debited from account 95008...               benign
8  Transaction alert: Rs.4624 debited from accoun...               benign
9  Dear Customer, Indane Gas has detected Rs.3878...             kyc_scam

In [4]:
dataset.isnull().sum()

message_text    0
class_label     0
dtype: int64

In [5]:
dataset.shape

(7000, 2)

In [6]:
dataset.describe

<bound method NDFrame.describe of                                            message_text    class_label
0     New water meter installation scheduled at your...         benign
1     Your water account 5774836158 has no pending d...         benign
2     BOI Security: Transaction of Rs.2135 from acco...  impersonation
3     BWSSB Notice: Pending water bill Rs.20462 for ...       kyc_scam
4     KYC expired. Update within 2 hours to avoid ac...  phishing_link
...                                                 ...            ...
6995  Gas subsidy of Rs.271 credited to your account...         benign
6996  BWSSB Notice: Pending water bill Rs.10188 for ...       kyc_scam
6997  Water Connection Suspension Notice: Account 72...  impersonation
6998  Payment received for electricity bill Rs. 6991...         benign
6999  Gas bill for February generated: Rs.18155 for ...         benign

[7000 rows x 2 columns]>

In [7]:
dataset.describe()

                                             message_text class_label
count                                                7000        7000
unique                                               6739           6
top     Safety advisory: Check hose & regulator period...      benign
freq                                                   68        3184

In [10]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   message_text  7000 non-null   str
 1   class_label   7000 non-null   str
dtypes: str(2)
memory usage: 109.5 KB

In [60]:
dataset = dataset.copy()

dataset = dataset.dropna(subset=["message_text"])
dataset = dataset[dataset["message_text"].str.strip() != ""]

In [61]:
x = dataset.iloc[:,:-1]
y = dataset["class_label"]

In [62]:
vectorizer = TfidfVectorizer(max_features=5000)
x_converted = vectorizer.fit_transform(x)

In [63]:
models = {
    "LR": LogisticRegression(),
    "NB": MultinomialNB(),
}

In [64]:
for name, model in models.items():
    score = cross_val_score(model, x_converted, y, cv=5).mean()
    print(name, score)

ValueError: Found input variables with inconsistent numbers of samples: [1, 7000]

In [65]:
x_converted.shape

(1, 1)